### ISSUE TITLE
Other economic changes

### ISSUE THREAD

**Issue by jrising** [openmodels/mimi-page-2020.jl#10]
(ii) considerably downscaled saturation limit for the impacts; (iii) modified uncertainty range for the “business as usual” emissions scenario, which is used as a reference point for calculating the abatement costs, covering the range roughly between RCP6.0 and a pathway exceeding RCP8.5

**Comment by jrising** [comment]
Is there anything else that needs to be changed for this issue?

**Comment by fhdezram** [comment]
Not from my perspective

**Comment by jrising** [comment]
Great!
