### ISSUE TITLE
Revise MAC curve

### ISSUE THREAD

**Issue by jrising** [openmodels/mimi-page-2020.jl#11]
revised present-day marginal abatement cost (MAC) curves, technological learning rate (CO2 only) and autonomous technological change based on energy efficiency improvements

**Comment by ColinCharlton** [comment]
Comparing the differences in documentation between PAGE-09 and PAGE-ICE, revisions need to be made to 4 parameters: Cutbacks at negative cost, most negative cost cutback, max cutbacks at positive   cost, and maximum cutback cost. Moreover, a new parameter 'learning for 2xExperience stock' has been added to PAGE-ICE.

PAGE-ICE also contains 4 new parameters to incorporate technological evolution into the MAC curve estimates. Values for those parameters must be updated.

PAGE-ICE contains no new documentation regarding changes to the MAC curve formulas.

**Comment by jrising** [comment]
When you're ready, make sure that your AbatementCosts_update.jl is renamed to just replace AbatementCosts.jl.  Thanks!

**Comment by jrising** [comment]
This is now finished, with PR #25 .
