### ISSUE TITLE
For SCC calculation: follow pulse values

### ISSUE THREAD

**Issue by jkikstra** [openmodels/mimi-page-2020.jl#29]
@P-Wlich @jkikstra 
Follow how the CO2 pulse affects values throughout the model to identify the origin of the impacts and check that there are no inconsistencies.
Goal: create a nice overview (maybe a visualisation) of the calculation of the SCC.

**Comment by pwaidelich** [comment]
Closing this as SCC calculation is now implemented using `compute_scc()`
