### ISSUE TITLE
For annualised PAGE: pick interpolation mode for each parameter

### ISSUE THREAD

**Issue by pwaidelich** [openmodels/mimi-page-2020.jl#31]
The current version of annualised PAGE uses linearly interpolated data. This might be appropriate for some parameters, but for others exponential interpolation will be better suited. So for each parameter with a time dimension in the /data/ folder and in data/rcps and data/ssps, we have to decide how interpolation will be conducted.
Ideally would be to end up with a csv file with two columns, one containing the file name for the parameter in /data/ and the other one stating "linear" or "exponential". I can then feed this into the input annualiser script, such that the interpolation technique is adjusted automatically.

**Comment by jkikstra** [comment]
this issue has been addressed in PR #48 , specifically [this commit](https://github.com/openmodels/mimi-page-2020.jl/pull/48/commits/29f73f99d1590d22dafe2a879f7a4f519b825714) and later [this commit](https://github.com/openmodels/mimi-page-2020.jl/pull/48/commits/fc1460cda029053b393b6e2e564f8fe002969501).
