### ISSUE TITLE
Update validation data for PAGE market damages

### ISSUE THREAD

**Issue by jrising** [openmodels/mimi-page-2020.jl#38]
The tests are currently failing just because of the non-Burke market damages test. When I setup the validation data for this test, I just took is straight from the excel, which shows all 0's, when that damages path is turned off. However a previous fix got these damages working, and not reporting all 0's, and now we need new validation data. Specifically, it should be for the NDCs scenario, but where damages are set to use the PAGE approach.

@jkikstra This is the only current bug in the unit tests.

**Comment by jkikstra** [comment]
This was implemented [here](https://github.com/openmodels/mimi-page-2020.jl/commit/1ecf3bde884a0f0a50167ebbe7fd161ae307da5b) for [updating PAGE-ICE to PAGE-2020](https://github.com/openmodels/mimi-page-2020.jl/pull/48). 
(see [comment](https://github.com/openmodels/mimi-page-2020.jl/pull/34#issuecomment-588202280))
