### ISSUE TITLE
For SCC calculation: SCC for annualised version

### ISSUE THREAD

**Issue by jkikstra** [openmodels/mimi-page-2020.jl#39]
@jrising I would like to be able to calculate the SCC using the new values from the annualised version, especially in my (future) comparisons between _non-variability_ and _variability_ versions.
However, the scc_calculation right now uses e.g. `create_marginal_model()`, which (I assume) uses `time` etc. 
Do you have a suggestion on how to go about this? 
Should I try to write something myself instead, or is there a way that I can still use code from `compute_scc.jl`?

**Comment by jrising** [comment]
It looks like your annualized version doesn't use annual emissions, is that right? If so, it shouldn't matter if your final results are produced by annual calculations, and you can just use it.

By the way, the code for create_marginal_model and that whole system is super simple. It doesn't use `time`. All it does is that if you ask for a variable's value, it returns the difference between the base model and the marginal model (which start out identical, and the user needs to make different), divided by the pulse size.

**Comment by jkikstra** [comment]
Forgot to comment on this, but everything seems to be working just fine now; the error indeed went away after simply restarting Julia....

Just for the record; I will indeed simply use the timestep version for calculating the SCC as there are no annualisation changes 'downstream' of the ClimateTemperature.jl component.
