### ISSUE TITLE
Update TCR, FRT, and ECS parameters

### ISSUE THREAD

**Issue by jrising** [openmodels/mimi-page-2020.jl#4]
adjusted transient climate response (TCR), feedback response time (FRT) and ECS parameter ranges according to IPCC AR5 based on CMIP5 results

**Comment by pwaidelich** [comment]
The formula to compute ECS remains identical to the one in PAGE09. The defaults for FRT and TCR (called "frt_warminghalflife" and "tcr_transientresponse") are set in the ClimateTemperature component (lines 12-13) for the deterministic version and their triangular distribution parameters are set in the msc file in lines 50-51. The defaults equal the mean of the respective distribution (= [min + mode + max]/3).
Hence, the distribution parameters (min, mode, max) should be switched to the ones given by Dmitry (FRT: 10, 20, 55; TCR: 0.8, 1.8, 2.7) and the defaults should be switched to the resulting means, i.e. to 28.333... and 1.7666...
ECS will adapt endogenously.

**Comment by jrising** [comment]
Awesome.  One pit-fall that we ran into (multiple times) is that the values reported in documents or visible in the Excel cells do not reflect the full precision of the numbers that are actually in those Excel cells.  (And then small numerical errors would get compounded and our tests for consistency with Excel would fail.)  Make sure that when you're updating the numbers, you grab the full precision from the PAGE Excel file.

**Comment by jrising** [comment]
This looks to be done.  Thanks!
