### ISSUE TITLE
Specify pulse size per year

### ISSUE THREAD

**Issue by jkikstra** [openmodels/mimi-page-2020.jl#58]
Currently, the pulse size the user has to specify as input is in terms of total Mt of emitted CO2 in the specific PAGE timestep. 
It would be more intuitive, especially when using different pulse years (with different period lengths) if this was changed to per year input. (Admittedly, this does make it less explicit that the actual pulse will be bigger, scaled with the length of the period.)

**Comment by jrising** [comment]
I actually think your parenthetical point is why it's not done this way. What we care about is the total pulse, not the pulse per year. Ideally, the pulse would always be over a single year anyway, so enshrining a concept of "pulse per year" seems counterproductive.

**Comment by jkikstra** [comment]
Alright - I agree with that this prevents it from misinterpreting what the model is doing. 
So let's close this issue and just take it as a note for future PAGE development.
